jobs:
  benefit: 'benefit'
  description: 'full_desc'
  short_desc: 'short_desc'
  name: 'name'
  salary: 'salary'
  location_id: 'location_id'
  contact_email: 'contact_email'
  contact_name: 'contact_name'
  contact_phone: 'contact_phone'

root_path_file: /home/haulv/working/training/venjob-training/

ftp_server:
  host_name: "192.168.1.156"
  user_name: "training"
  password: "training"

crawl_log_file: /home/haulv/working/training/venjob-training/log/crawler/failure_urls.log

css_tree:
  parent: 'div.MyJobLeft'
  tags:
    name: 'div.top-job-info'
    created_at: 'div.datepost'
    title: '[itemprop="title"]'
    job_details: 'ul.DetailJobNew'
    benefit: 'ul.list-benefits'
    short_desc: '[itemprop="description"]'
    description: 'div.MarBot20'
    company name: 'div.tit_company'
    company address: '[itemprop="addressLocality"]'
    introductions: '[id="emp_more"]'

URL_BATCH_SIZE: 50

job_patern:
  category: ^([\w|\W]*)(Ngành nghề:)([\w|\W]+)
  salary: ^([\w|\W]*)(Lương:)([\w|\W]+)
  company province: ^([\w|\W]*)(Nơi làm việc:)([\w|\W]+)

solr_url: http://localhost:8983/solr/venjob

field_search:
  title: 7
  description: 6
  company_name: 5
  city_name: 4
  introductions: 3
  address: 2
  industry: 5
  salary: 1
