jobs:
  benefit: 'benefit'
  description: 'full_desc'
  name: 'name'
  salary: 'salary'
  location_id: 'location_id'
  contact_email: 'contact_email'
  contact_name: 'contact_name'
  contact_phone: 'contact_phone'

root_path_file: /home/haulv/working/training/venjob-training/

ftp_server:
  host_name: "192.168.1.156"
  user_name: "training"
  password: "training"

crawl_log_file: /home/haulv/working/training/venjob-training/log/crawler/failure_urls.log

css_tree:
  parent: 'div.MyJobLeft'
  tags:
    name: 'div.top-job-info'
    created_at: 'div.datepost'
    'company province': '[itemprop="jobLocation"]'
    title: 'div.top-job-info'
    category: '[itemprop="industry"]'
    salary: 'ul.DetailJobNew'
    benefit: 'ul.list-benefits'
    description: '[itemprop="description"],[itemprop="experienceRequirements"]'
    'company name': '[itemprop="name"]'
    'company address': '[itemprop="addressLocality"]'
    introductions: '[id="emp_more"]'

URL_BATCH_SIZE: 5000