# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d129155b8b5113ae5b99ff637e5b7d0b54ab61abb5e7726b2ded1d770830e034ae33073ca036ab750f943fb7315b0b4f63821e2529e108bd6d1f2b4fc04cf90c

test:
  secret_key_base: a3004b746e4037237cf6efc46bef83121bd0c7c811bf45a4ab9f01bf6f3184f6d72a3a480ada78d6eb53ddf6e8cabfc145bf4f5c0a3b5834263ff3693bfd8078

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
